
4.times do
Card.create(value: 2, name: "Two")
Card.create(value: 3, name: "Three")
Card.create(value: 4, name: "Four")
Card.create(value: 5, name: "Five")
Card.create(value: 6, name: "Six")
Card.create(value: 7, name: "Seven")
Card.create(value: 8, name: "Eight")
Card.create(value: 9, name: "Nine")
Card.create(value: 10, name: "Ten")
Card.create(value: 11, name: "Jack")
Card.create(value: 12, name: "Queen")
Card.create(value: 13, name: "King")
Card.create(value: 14, name: "Ace")
end
Player.create(name: "Darrin", password: "test", win_record: 6)
Player.create(name: "Kevin", password: "test", win_record: 8)
Player.create(name: "Sam", password: "test", win_record: 10)
Player.create(name: "Bunday", password: "test", win_record: 11)
Player.create(name: "Jon", password: "test", win_record: 4)
Player.create(name: "Pearl", password: "test", win_record: 7)
Player.create(name:"Computer", password: "I_am_a_computer")
